
project_id = "tghmaigxcrnhyjzvjpvc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
additional_redirect_urls = ["https://127.0.0.1:3000"]
api_key_name = "service_role"
jwt_expiry = 3600
password_min_length = 6
external_phone_enabled = true
sms_test_otp = "123456"

[auth.email]
template = { invite = "Hello", confirmation = "Hello", recovery = "Hello", magic_link = "Hello", email_change = "Hello" }

[edge_functions]
enabled = true

[functions.militaries]
import_map = "supabase/functions/import_map.json"

[functions.processes]
import_map = "supabase/functions/import_map.json"

[functions.sync-history]
import_map = "supabase/functions/import_map.json"
